# Generated by Django 4.1.4 on 2024-03-23 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_auth', models.CharField(max_length=255)),
                ('c_password', models.CharField(max_length=50)),
                ('client_id', models.CharField(db_column='client_id', max_length=20)),
            ],
            options={
                'db_table': 'client_auth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SstplDownData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_column='client_id', max_length=20)),
                ('time', models.DateTimeField(db_column='Time', default=django.utils.timezone.now)),
                ('deveui', models.CharField(db_column='deveui', max_length=16)),
                ('command', models.CharField(db_column='command', max_length=512)),
            ],
            options={
                'db_table': 'SSTPL_Down_Data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SstplUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('modulation', models.CharField(blank=True, max_length=100, null=True)),
                ('data_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('code_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('lora_snr', models.FloatField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('port_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'SSTPL_UP_Data',
                'managed': True,
            },
        ),
    ]
